%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 2  

imu_topic: "/mynteye/imu/data_raw"
image0_topic: "/mynteye/left/image_raw"
image1_topic: "/mynteye/right/image_raw"
output_path: "/your/local/path/"

image_width: 640 
image_height: 400

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
#acc_n: 0.1          # accelerometer measurement noise standard deviation. 
#gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
#acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
#gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
#g_norm: 9.81007     # gravity magnitude

#acc_n: 0.0268014618074         # accelerometer measurement noise standard deviation. #0.599298904976
#gyr_n: 0.00888232829671        # gyroscope measurement noise standard deviation.     #0.198614898699
#acc_w: 0.00262960861593         # accelerometer bias random work noise standard deviation.  #0.02
#gyr_w: 0.000379565782927       # gyroscope bias random work noise standard deviation.     #4.0e-5
#g_norm: 9.81007     # gravity magnitude

acc_n: 2.1657228523252730e-02          # accelerometer measurement noise standard deviation. #0.599298904976
gyr_n: 2.1923690143745844e-03        # gyroscope measurement noise standard deviation.     #0.198614898699
acc_w: 3.8153871149178200e-04         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.4221215955051228e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/tiny/vins_fusion/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

use_mynteye_adapter: 1
# mynteye_imu_srv: "s2"

# ==================================================================
# Following contents will be auto adapter when you use mynteye sdk.
# ==================================================================

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., -4.1300000000000003e-02,
           0., 1., 0., -2.8500000000000001e-03,
           0., 0., 1., -1.0000000000000000e-02,
           0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., 3.8699999999999998e-02,
           0., 1., 0., -2.8500000000000001e-03,
           0., 0., 1., -1.0000000000000000e-02,
           0., 0., 0., 1. ]

#body_T_cam0: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [ -9.9997682265467325e-01, 6.5076367365944354e-03,
#       2.0012040300038079e-03, 3.0710470880745057e-02,
#       -6.5115707349528967e-03, -9.9997686761696203e-01,
#       -1.9656239551802640e-03, -1.1619184937249040e-02,
#       1.9883661707245873e-03, -1.9786093788315136e-03,
#       9.9999606574470934e-01, 1.3708056410108752e-02, 0., 0., 0., 1. ]
#body_T_cam1: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [ -9.9996481469059639e-01, 7.5082204823142557e-03,
#       3.7411236265824004e-03, -4.8372430610697889e-02,
#       -7.5294931542847846e-03, -9.9995537938366685e-01,
#       -5.7049079314248205e-03, -1.2162086098338444e-02,
#       3.6981229887599635e-03, -5.7328759672098219e-03,
#       9.9997672873897647e-01, 1.0449454342939922e-02, 0., 0., 0., 1. ]


#cam0_calib: "left_pinhole.yaml"
#cam1_calib: "right_pinhole.yaml"
cam0_calib: "left_equ.yaml"
cam1_calib: "right_equ.yaml"
# cam0_calib: "device_params_left.yaml"
# cam1_calib: "device_params_right.yaml"
#cam0_calib: "left_mei.yaml"
#cam1_calib: "right_mei.yaml"
